### ISSUE TITLE
device-side assert triggered at THCStorage.c

### ISSUE THREAD

**Issue by bvraghav** [pytorch/examples#342]
I had started with this train example as template:
https://github.com/pytorch/examples/blob/master/imagenet/main.py

Applied the following tweaks:
1. commented out all distributed computing
2. Fixed my dataset loader. Separately created it and tested that it works.
3. Tweaked the train loop for parallel processing of the pre-processing transforms.
4. Tweaked the train loop to glue with the customized dataset loader [1].
5. Used logging api instead of print statements.

When invoked from commandline, the training loop runs for some number of passes, and then fails with the following backtrace:
```
/build/python-pytorch/src/pytorch-0.3.1-py3-cuda/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, signed long *, Dtype *, int, int, int, int, signed long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/build/python-pytorch/src/pytorch-0.3.1-py3-cuda/torch/lib/THC/generic/THCStorage.c line=36 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 457, in <module>
    main()
  File "train.py", line 207, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 265, in train
    losses.update(loss.data[0], input_var.size(0))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /build/python-pytorch/src/pytorch-0.3.1-py3-cuda/torch/lib/THC/generic/THCStorage.c:36
```
The error stack is same at each failure, but the failure may occur any time during the training, ranging from 2k to 32k mini-batches. No specific pattern of failure. Also if it is useful; the memory usage was about 5G on one GPU with batch-size of 128, and cache-length of 16384 input samples. Any insights?

[1] _Customized Dataset Loader_: The dataset is 4.5M samples in h5 format. The loader loads a part of it, say 16384 samples in one go, and feeds it to 128 batches of 128 samples each. I call this as  one _cache pass_ (Sorry for the shabby name. I recall now that it interferes with _forward_ and _backward pass_) . Then the loader reloads. This principle is implemented partly using the pytorch dataset api, and partly, by splitting  the epoch into multiple passes --- just another for loop nested inside of the epoch.

**Comment by seongkyun** [comment]
I have the same issue as like you.
The problem was the files in the Imagenet training/validation files.
Just remove tar files in the each training/validation folder include including folders.

It works for me :)

**Comment by bvraghav** [comment]
I do not remember now whether I discovered the root cause, resolved it or circumvented it... This seems to be an old story... But I was certainly not using the imagenet dataset.

So I guess it would be wise to close the issue from my end.

Thanks

**Comment by monghimng** [comment]
> I have the same issue as like you.
> The problem was the files in the Imagenet training/validation files.
> Just remove tar files in the each training/validation folder include including folders.
> 
> It works for me :)

Works for me too! I think it was because of the way the data loader was looking for the training samples. The error states that the labels t are not given from 0 to max_label. This is because there is no label for the tar files!
