### ISSUE TITLE
stuck at test ImageNet?

### ISSUE THREAD

**Issue by culurciello** [pytorch/examples#56]
Hi, I run ImageNet training successfully for 1 epoch but then it got stuck at testing, with no error message, did this happen to you?

**Comment by edouardoyallon** [comment]
hi, yes, remove the pin memory when there is a multi gpu

**Comment by colesbury** [comment]
No -- setting `pin_memory=True` is most useful when using more than one GPU so that the copies to each GPUs can overlap with each other.

@culurciello, what's the traceback when it gets stuck?

**Comment by edouardoyallon** [comment]
@colesbury I'm not saying why this is happening, but basically (and it happens only on multi GPU hardware, for me), at the first batch of the test at the first epoch, suddenly the screen freezes, and the memory is not released. Which, I think due to the pin memory, or at least it has solved the issue to set if to false. It's not clear to me why it happens!

**Comment by culurciello** [comment]
I run this a second time, and it worked. I was orignally using resnet18, but with Alexnet and resnet50 it works fine.

**Comment by zym1010** [comment]
so has anyone figured out why? I'm experiencing a similar issue, as in #148

**Comment by micklexqg** [comment]
same problem,  did anyone solve it?
