### ISSUE TITLE
Problem on multiple nodes

### ISSUE THREAD

**Issue by ElegantLin** [pytorch/examples#611]
Hi, when I am running ImageNet example on multiple nodes, I met the problem showing 
`RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error` on my node 0.

The command I used is 
`python main.py -a resnet50 --dist-url 'tcp://IP_OF_NODE0:FREEPORT' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 0 [imagenet-folder with train and val folders]`

The platform I used is `Python 3.6` using Anaconda on CentOS and the PyTorch Version is `1.1.0`.

Actually, I met this problem on single node and multi GPUs but I solved it by setting
`export NCCL_P2P_DISABLE=1`.

Also before I ran the code, I would set `OMP_NUM_THREADS=1` to make the distributed training faster. 

I made sure that my IP and port were correct.

Do you know how to solve it? 

Thanks

**Comment by kealennieh** [comment]
I've got the same error. Have you solved this problem ?

**Comment by ElegantLin** [comment]
Yes, I updated to `Pytorch 1.2` and this problem was solved.
