### ISSUE TITLE
run examples/imagenet/main.py on Multiple nodes,NCCL error

### ISSUE THREAD

**Issue by ljz756245026** [pytorch/examples#926]
When I run examples/imagenet/main.py
I run on Multiple nodes:
node0 :
```
NVIDIA_VISIBLE_DEVICES=0,1 python image_main.py -a resnet50 --dist-url 'tcp://IP:PORT' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 0 tiny-imagenet-200
```

node1:
```
NVIDIA_VISIBLE_DEVICES=0,1 python image_main.py -a resnet50 --dist-url 'tcp://IP:PORT' --dist-backend 'nccl' --multiprocessing-distributed --world-size 2 --rank 1 tiny-imagenet-200
```

on node 1, some errors like:
```
Traceback (most recent call last):
  File "image_main.py", line 429, in <module>
    main()
  File "image_main.py", line 109, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/jinzhang/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jinzhang/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/jinzhang/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/jinzhang/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/jinzhang/image_main.py", line 153, in main_worker
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
  File "/home/jinzhang/anaconda3/envs/myenvs3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1623448224956/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
```

my environment is:
```

Package            Version
------------------ -------------------
certifi            2021.5.30
charset-normalizer 2.0.3
click              8.0.1
datasets           1.10.2
dill               0.3.4
fairscale          0.3.8
filelock           3.0.12
fsspec             2021.7.0
huggingface-hub    0.0.12
idna               3.2
importlib-metadata 4.6.1
joblib             1.0.1
mkl-fft            1.3.0
mkl-random         1.2.2
mkl-service        2.4.0
multiprocess       0.70.12.2
numpy              1.20.3
olefile            0.46
packaging          21.0
pandas             1.3.0
Pillow             8.3.1
pip                21.1.3
portalocker        2.0.0
pyarrow            4.0.1
pyparsing          2.4.7
python-dateutil    2.8.2
pytz               2021.1
PyYAML             5.4.1
regex              2021.7.6
requests           2.26.0
sacrebleu          1.5.1
sacremoses         0.0.45
setuptools         52.0.0.post20210125
six                1.16.0
tokenizers         0.10.3
torch              1.9.0
torchaudio         0.9.0a0+33b2469
torchvision        0.10.0
tqdm               4.61.2
transformers       4.10.0.dev0
typing-extensions  3.10.0.0
urllib3            1.26.6
wheel              0.36.2
xxhash             2.0.2
zipp               3.5.0
```

I want to know how to solve this problem

**Comment by ljz756245026** [comment]
I have solved this problem.
This problem is caused by firewall. I test some methods to configure the firewall. It is really time-consumption.
Finally, the easiest way is close the firewall when training the model.
run the following command on both 2 nodes.
```
systemctl stop firewalld
```

after training, you can open the firewall again.
